[mgr]
cwd = {{ fg = "{color4}" }}
hovered         = {{ fg = "{color0}", bg = "{color4}" }}
find_keyword  = {{ fg = "{color10}", italic = true }}
find_position = {{ fg = "{color3}", bg = "reset", italic = true }}
marker_selected = {{ fg = "{color10}", bg = "{color10}" }}
marker_copied   = {{ fg = "{color10}", bg = "{color10}" }}
marker_cut      = {{ fg = "{color9}", bg = "{color9}" }}
tab_active   = {{ fg = "{color0}", bg = "{color8}" }}
tab_inactive = {{ fg = "{color7}", bg = "{color0}" }}
border_style  = {{ fg = "{color8}" }}

[status]
separator_style = {{ fg = "{color0}", bg = "{color0}" }}
mode_normal = {{ fg = "{color0}", bg = "{color7}", bold = true }}
mode_select = {{ fg = "{color0}", bg = "{color10}", bold = true }}
mode_unset  = {{ fg = "{color0}", bg = "{color13}", bold = true }}
progress_label  = {{ fg = "{foreground}", bold = true }}
progress_normal = {{ fg = "{color8}", bg = "{color0}" }}
progress_error  = {{ fg = "{color9}", bg = "{color0}" }}
permissions_t = {{ fg = "{color8}" }}
permissions_r = {{ fg = "{color10}" }}
permissions_w = {{ fg = "{color9}" }}
permissions_x = {{ fg = "{color10}" }}
permissions_s = {{ fg = "{color8}" }}

[input]
border   = {{ fg = "{color7}" }}
selected = {{ reversed = true }}

[select]
border   = {{ fg = "{color8}" }}
active   = {{ fg = "{color3}" }}

[tasks]
border  = {{ fg = "{color8}" }}
hovered = {{ underline = true }}

[which]
mask            = {{ bg = "{color0}" }}
cand            = {{ fg = "{color4}" }}
rest            = {{ fg = "{color8}" }}
desc            = {{ fg = "{color3}" }}
separator_style = {{ fg = "{color8}" }}

[help]
on      = {{ fg = "{color3}" }}
exec    = {{ fg = "{color4}" }}
desc    = {{ fg = "{color8}" }}
hovered = {{ bg = "{color8}", bold = true }}
footer  = {{ fg = "{color0}", bg = "{color7}" }}

[filetype]
rules = [
    {{ mime = "image/*", fg = "{color4}" }},
    {{ mime = "video/*", fg = "{color10}" }},
    {{ mime = "audio/*", fg = "{color10}" }},
    {{ mime = "application/zip",             fg = "{color3}" }},
    {{ mime = "application/gzip",            fg = "{color3}" }},
    {{ mime = "application/x-tar",           fg = "{color3}" }},
    {{ mime = "application/x-bzip",          fg = "{color3}" }},
    {{ mime = "application/x-bzip2",         fg = "{color3}" }},
    {{ mime = "application/x-7z-compressed", fg = "{color3}" }},
    {{ mime = "application/x-rar",           fg = "{color3}" }},
    {{ name = "*",  fg = "{color7}" }},
    {{ name = "*/", fg = "{color4}" }}
]

