# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
preview_hovered = { underline = true }
tab_width    = 1
border_symbol = "│"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""

# : }}}


# : Input {{{

[input]
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
separator       = "  "

# : }}}


